---

- name: Install Nginx
  apt:
    name: "{{ item }}"
    state: "present"
    install_recommends: True
  loop:
    - "nginx"
 
 
- name: Generate nginx conf file
  template:
    src: "habarshi.conf.j2"
    dest: "/etc/nginx/conf.d/{{ habarshi_domain }}.conf"
    owner: "root"
    group: "root"
    mode: "0644"
  notify: ["Restart NGINX"]
