---

docker_edition: "ce"
docker_channel: "stable"

docker_version: "18.03.1"
docker_install_docker_compose: True
docker_compose_version: "1.21.1"

docker_users: []

docker_cron_tasks:
  - job: docker system prune -f
    name: "Docker clean up"
    schedule: ["0", "0", "*", "*", "0"]

docker_daemon_options: []
docker_daemon_environment: []

docker_apt_key: "0EBFCD88"
docker_repository: "deb [arch=amd64] https://download.docker.com/linux/{{ ansible_distribution | lower }} {{ ansible_distribution_release }} {{ docker_channel }}"
docker_apt_package_name: "{{ docker_version }}~{{ docker_edition }}-0~{{ ansible_distribution | lower }}"

docker_apt_cache_time: 86400
